### PR TITLE
fix: getReferenceSchema for names with '.' chars

### LINKED ISSUE #140: [bug] if the schema name has '.' in the name then throws: Internal Error: #/components/schemas/Name.With.Dots not found!
good news, its a simple fix. i tested it out directly in the lib source itself and got it working.

the issue arises from [this line](https://github.com/fabien0102/openapi-codegen/blob/main/plugins/typescript/src/core/getReferenceSchema.ts#L24)

what is happening is that a model with `.` in its name (something ive inherited in an internal API as a resolution to schema name conflicts) is treated by the `lodash.get` method as a path traversal. 

so for example `Name.With.Dots` as the model name would be searching for an object looking like this

```js
{
  components: {
    schemas: {
      Name: {
        With: {
          Dots: ...
        }
      }
    }
  }
}
```

when in reality the actual target is

```js
{
  components: {
    schemas: {
      'Name.With.Dots': ...
    }
  }
}
```

the fix uses the default result argument of `lodash.get` to see if it can be found through direct access. i did some testing to see if there is ever a case where `components.schema` is undefined and didnt find any but to protect against a case others might encounter we do some undefined / null checking:

```ts
export const getReferenceSchema = (
  $ref: string,
  openAPIDocument: Pick<OpenAPIObject, "components">
): SchemaObject => {
  const [hash, ...refPath] = $ref.split("/");
  if (hash !== "#") {
    throw new Error("This library only resolve local $ref");
  }

  // refPath.at(-1) is the actual name being searched for, where [0] is 'components' and [1] is 'schemas'
  const defaultDirectSearch = openAPIDocument?.components?.schemas && openAPIDocument.components.schemas[refPath.at(-1)];
  const referenceSchema = get(openAPIDocument, refPath.join("."), defaultDirectSearch);

  if (!referenceSchema) {
    throw new Error(`${$ref} not found!`);
  }

  ...
};
```

### PR DESCRIPTION
**Pull request by ci-vamp**
fixes #140

### CODE REVIEW

**Review by fabien0102 — CHANGES_REQUESTED** [review]
Thanks for the contribution! Let’s just add a little unit test to make sure this is working as expected 😃

**Comment by quyctd** [comment]
@fabien0102 Hi, it seems the test was added, could you recheck the PR? I'm facing this issue and depressed that nothing working :(

**Comment by fabien0102** [comment]
Sorry I was on vacation last week, looks good, I can finish the PR to merge it this week!

**Review by fabien0102 — APPROVED** [review]

**Comment by fabien0102** [comment]
Let’s merge this! Thx for the contribution 🚀

**Pull request merged**
