### PR TITLE
chore: documentation

### PR DESCRIPTION
**Pull request by needim**
related #105

### CODE REVIEW

**Comment by needim** [comment]
worth mentioning:

- fetcher and context only generated once for userland.
- you should modify your fetcher and context for your own needs.
- on init if you choose Typescript Types it only generates Types
- on init if you choose Generic Fetchers it generates Types and Fetchers
- on init if you choose React Query Components it generates Types and Fetchers and React Query Components
- adding terminal init gif to readme can help users to understand what the init function actually does
- better collapsable readme for sections "What do you want to generate?" (for example)
  - Types
  - Fetchers
  - React Query

**Comment by ANDREYDEN** [comment]
@needim Would table of contents fit into this PR?

**Comment by needim** [comment]
Of course!

**Comment by needim** [comment]
example gif demo.

openapi-codegen-init

**Review by fabien0102 — APPROVED** [review]
👌

**Comment by ANDREYDEN** [comment]
@needim, I added [some suggestions](https://github.com/needim/openapi-codegen/pull/1) to your branch.

**Comment by needim** [comment]
proposal: more declarative wordings in the init function:

- Types
- Types & Fetchers
- Types & Fetchers & React Query hooks

**Comment by ANDREYDEN** [comment]
> proposal: more declarative wordings in the init function:
> 
> * Types
> * Types & Fetchers
> * Types & Fetchers & React Query hooks

@needim I would suggest having 3 options (Types, Fetchers, React Query hooks) and have a multiselect functionality (spacebar to add an option, enter to submit). You can refer to the Firebase CLI for an example.

**Comment by fabien0102** [comment]
This looks good enough to be merge, let’s merge and iterate on further PRs :)

**Pull request merged**
