### PR TITLE
Add v5 generator

### LINKED ISSUE #176: Support for react query 5
React query is currently working on v5 and API seems to be stable.

https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5 

Would it be possible to add version to the generator?

### PR DESCRIPTION
**Pull request by rajzik**
Fixes #176 

Added generator for react query V5

### CODE REVIEW

**Comment by fabien0102** [comment]
Hey,
First of all, thanks for the PR!
Looking at the migration guide from react-query https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5 they did remove some signatures.
This means, if I’m following properly that the v5 object version should work with the v4. In this case, let’s just update to the object signature, and we should be good to go 😃 

The underline idea is to keep this project as easy as possible, it’s a side project so if I don’t have to maintain multiple version of react-query, this would be amazing 😁

**Comment by rajzik** [comment]
Oh I see, I will change it tomorrow and test it on our project.

**Comment by rajzik** [comment]
Ok, the object signature works fine, I've update the PR, feel free to add any comments to it, so I can fix it. 
If the PR is fine I would love to see this released soon. Thank you.

**Review by fabien0102 — APPROVED** [review]
Looks good!

**Comment by fabien0102** [comment]
> I can see that pipeline failed, in repo is package lock and pipeline uses yarn, should I change package lock to yarn lock and commit?

Yeah, let’s try, this is wierd…

**Comment by essuraj** [comment]
this version works with react query 4 but fails with react query 5

**Comment by fabien0102-crabnebula** [comment]
At least this is not breaking react-query v4, sorry for bad review!

**Comment by rajzik** [comment]
I think this is issue of RQ, UseQueryOptions should be assignable to the useQuery hook, I've opened issue in tanstack/query https://github.com/TanStack/query/issues/5696

**Pull request merged**
