### PR TITLE
updated all dep and fixed all vulnerabilities

### PR DESCRIPTION
**Pull request by el-j**
before and after:
image

### CODE REVIEW

**Comment by el-j** [comment]
update is done with `ncu --doctor`

**Comment by el-j** [comment]
image
image

**Comment by el-j** [comment]
@fabien0102 are u still maintaining this? I just use it now again for a frontend and like it very much again ;)

**Comment by fabien0102** [comment]
> @fabien0102 are u still maintaining this? I just use it now again for a frontend and like it very much again ;)

I do! Thx for the ping (sorry I don't have a lot of time for side project lately…)

**Comment by fabien0102** [comment]
Amazing contribution, thx a lot!!! 😍

**Comment by fabien0102** [comment]
I'm trying to deploy a new version on npm (my god this project need a bit of love, everything is so old ^^)

**Pull request merged**
