### PR TITLE
fix: Camel case query function operation IDs

### PR DESCRIPTION
**Pull request by fb55**
Operation IDs in query functions currently don't line up with keys in the `QueryOperation` object.

### CODE REVIEW

**Review by fabien0102 — APPROVED** [review]
Looks good 👌 I guess all my operationId were already camelCase, so I never spot issue ^^

**Comment by fb55** [comment]
@fabien0102 Could this possibly be released on npm?

**Comment by fabien0102** [comment]
Strange, the release-bot was not triggered… let me see what I can do

**Comment by fabien0102-crabnebula** [comment]
https://github.com/fabien0102/openapi-codegen/pull/247#issuecomment-2082250087

Should be there! Sorry for the delay

**Pull request merged**
