### PR TITLE
update prettier

### PR DESCRIPTION
**Pull request by nikravi**
This PR fixes the tailwind prettier plugin if it's used on the target repository,

https://github.com/fabien0102/openapi-codegen/issues/200

### CODE REVIEW

**Comment by fabien0102** [comment]
The lock file is not up-to-date…

**Comment by nikravi** [comment]
@fabien0102 @Karnak19 updated the PR, build and npm ci is ok now. Thank you

**Comment by owonwo** [comment]
Hi @fabien0102 when do you plan on publishing this update?

**Comment by weedgrease** [comment]
this is still an issue for users using prettier@^3.x.x in their projects - can we get some eyes on this @fabien0102?

it also seems strange to me that this package's prettier version has any impact on being able to run the cli anywhere considering prettier is a dev dependency

**Review by fabien0102 — APPROVED** [review]
Looks good, sorry for the very long review time…

**Comment by Karnak19** [comment]
Hello, for some reason the `cli` package still depends on `prettier@2.8.8` on my side 

```yml
# extracted from my pnpm-lock
 /@openapi-codegen/cli@2.0.0(@types/react@18.2.66)(react-dom@18.2.0)(react@18.2.0):
    resolution: {integrity: sha512-LPQPZ+zj+ExyLFsEhUL8T2a4bbq28Ftqu9vZEGgAg+s8fyH7HzImvwNudaZivZ3S8uyl+7/RhPFJjZ7nPzLAaQ==}
    hasBin: true
    dependencies:
      '@apollo/client': 3.9.7(@types/react@18.2.66)(graphql@15.8.0)(react-dom@18.2.0)(react@18.2.0)
      '@swc/core': 1.4.8
      case: 1.6.3
      chalk: 5.3.0
      cli-highlight: 2.1.11
      clipanion: 3.2.1(typanion@3.14.0)
      fs-extra: 10.1.0
      got: 12.6.1
      got-fetch: 5.1.8(got@12.6.1)
      graphql: 15.8.0
      ink: 3.2.0(@types/react@18.2.66)(react@18.2.0)
      js-yaml: 4.1.0
      openapi3-ts: 2.0.2
      prettier: 2.8.8
      rxjs: 7.8.1
      slash: 4.0.0
      swagger2openapi: 7.0.8
      tslib: 2.6.2
      typanion: 3.14.0
      typescript: 4.8.2
    transitivePeerDependencies:
      - '@swc/helpers'
      - '@types/react'
      - bufferutil
      - encoding
      - graphql-ws
      - react
      - react-dom
      - subscriptions-transport-ws
      - utf-8-validate
    dev: true
```

npmgraph also shows it:
https://npmgraph.js.org/?q=@openapi-codegen/cli#select=exact%3Aprettier%402.8.8

**Pull request merged**
