### PR TITLE
fix(issue-127): Also accept "default" as response status, next to "200"

### PR DESCRIPTION
**Pull request by bertyhell**
fixes: https://github.com/fabien0102/openapi-codegen/issues/127

Also allow default response types to be accepted next to the current 2xx response types in https://github.com/fabien0102/openapi-codegen/blob/main/plugins/typescript/src/core/getDataResponseType.ts#L33

### CODE REVIEW

**Review by fabien0102 — DISMISSED** [review]

**Comment by bertyhell** [comment]
hmm, default doesn't always correspond to a success response it seems according to the test:
```json
    const responses: ResponsesObject = {
      "200": {
        description: "pet response",
        content: {
          "application/json": {
            schema: {
              type: "array",
              items: {
                $ref: "#/components/schemas/Pet",
              },
            },
          },
        },
      },
      default: {
        description: "unexpected error",
        content: {
          "application/json": {
            schema: {
              $ref: "#/components/schemas/Error",
            },
          },
        },
      },
    };
```

So either we shouldn't accept default as a success state, or only if no other 2xx response states are found?
Maybe its better to stay strict and only accept 2xx and close this PR?

**Comment by fabien0102** [comment]
So far I never cross `default` for success responses and I can’t find anything about it in the official specs https://swagger.io/specification/

image
image

With this in mind, I think I prefer to stay strict and close this PR, thanks for your contribution anyway!

**Comment by fabien0102** [comment]
image

https://swagger.io/docs/specification/describing-responses/#default

I think I found the relevant part of the documentation! I guess, technically, `default` could describe a 2xx response 🤔 But I will not consider this a good practice, yeah let’s be strict for now (if the issue comeback I might reconsider).

As workaround, if you can’t fix the root cause, you can fix the specs "on the fly" in `openapi-codegen.config.ts`:

```ts
import {
  generateSchemaTypes,
  generateReactQueryFunctions,
} from "@openapi-codegen/typescript";
import { defineConfig } from "@openapi-codegen/cli";
import { OperationObject } from "openapi3-ts";

export default defineConfig({
  petstore: {
    from: {
      source: "url",
      url: "https://petstore3.swagger.io/api/v3/openapi.json",
    },
    outputDir: "src/petstore",
    to: async (context) => {
      // Use `200` instead of `default` response
      Object.entries(context.openAPIDocument.paths).forEach(
        ([_route, verbs]) => {
          Object.entries(verbs).forEach(([verb, operation]) => {
            if (!isVerb(verb) || !isOperationObject(operation)) return;
            operation.responses[200] = operation.responses.default;
            delete operation.responses.default;
          });
        }
      );

      const filenamePrefix = "petstore";
      const { schemasFiles } = await generateSchemaTypes(context, {
        filenamePrefix,
      });
      await generateReactQueryFunctions(context, {
        filenamePrefix,
        schemasFiles,
      });
    },
  },
});

export const isVerb = (
  verb: string
): verb is "get" | "post" | "patch" | "put" | "delete" =>
  ["get", "post", "patch", "put", "delete"].includes(verb);


/**
 * Type guard for `OperationObject`
 *
 * @param obj
 */
export const isOperationObject = (
  obj: any
): obj is OperationObject & { operationId: string } =>
  typeof obj === "object" && typeof (obj as any).operationId === "string";
```

**Comment by bertyhell** [comment]
Cool thx.

I was able to fix the root issue in nestjs
I just had to provide the status code to the swagger doc generator for each route.

**Pull request closed without merging**
